#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

ERRS=""

d="$(cd "$(dirname "$0")" ; pwd -P)"

project_id="$3"

head -n 1 "$2" | grep -qE '([ ,;:/]|^)#'"$1"'([ ,;:/]|$)' || ERRS="$ERRS
1: must mention \`#$1' somewhere (branch issue number)"

ERRS="$ERRS
$(head -n 1 "$2" | tr ' ,;:/' '\n' | grep '^#' | sed -re 's/[^0-9]//g' | grep -Ev '^'"$1"'$' | while IFS= read -r iid ; do
  db_iid="$(psql -A -t -d gitlab -c "SELECT iid FROM issues WHERE project_id = $project_id AND iid = $iid AND (state = 'opened' OR state = 'reopened')")"
  [ "$iid" = "$db_iid" ] || echo "1: \`#$iid' is not an open issue (and so can't be mentioned in commit _title_)"
done)"

ERRS="$(echo "$ERRS" | { grep -v '^$' || true; })"
if [ -n "$ERRS" ] ; then
  echo "$ERRS" | grep -v '^$'
  exit 1
fi
