#!/bin/sh

set -o noclobber
set -o errexit
set -o nounset

[ $# -lt 3 ] && { echo >&2 "$0: not meant to be run manually" ; exit 1 ; }

ref="$1"
oldsha="$2"
newsha="$3"

# if this is a deletion of a branch, exit immediately
[ "$newsha" = '0000000000000000000000000000000000000000' ] && exit 0

{
  # first, exclude commits reachable from the old sha, if there is any
  [ "$oldsha" = '0000000000000000000000000000000000000000' ] || echo "^$oldsha"

  # then, exclude commits reachable from all already known branches
  git for-each-ref --format '^%(refname:short)' 'refs/heads/'

  # TODO: what about known tags here? :o
} | xargs git rev-list --reverse "$newsha"
